apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: "jest-mongodb-node-app"
  labels:
    name: "jest-mongodb-node-app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "jest-mongodb-node-app"
  template:
    metadata:
      namespace: default
      labels:
        app: "jest-mongodb-node-app"  
    spec:
      containers:
      - name: "jest-mongodb-node-app"
        image: "pedrobotolli/jest-mongodb-node-example:1"
        resources:
          requests:
            memory: 512Mi
            cpu: 128m
          limits:
            memory: 1024Mi
            cpu: 256m
        envFrom:
        - secretRef:
            name: "jest-mongodb-node-secrets"
        ports:
          - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: "jest-mongodb-node-service"
  labels:
    app: "jest-mongodb-node-service"
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 3001
      targetPort: 3001
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: "jest-mongodb-node-app"
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: "jest-mongodb-node-service-cip"
  labels:
    app: "jest-mongodb-node-app"
spec:
  type: ClusterIP
  ports:
    # the port that this service should serve on
    - port: 3001
      targetPort: 3001
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: "jest-mongodb-node-app"
