apiVersion: v1
kind: Pod
metadata:
  name: "jest-mongodb-node-pod"
  labels:
    name: "jest-mongodb-node"
spec:
  containers:
  - name: "jest-mongodb-node-app"
    image: "us.icr.io/test-images/jest-mongodb-node-example:1.0"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    envFrom:
    - secretRef:
        name: "jest-mongodb-node-secrets"
    ports:
      - containerPort: 3001
